# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: | 
    docker run -p 8081:8081 \
    -p 10251:10251 -p 10252:10252 -p 10253:10253 -p 10254:10254  \
    -m 3g \
    --cpus=2.0 \
    --name=test-linux-emulator \
    -e AZURE_COSMOS_EMULATOR_PARTITION_COUNT=1 \
    -e AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true \
    -it mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'src/MyApplication/MyApplication.UnitTest/MyApplicationIntegrationTests.csproj'
    testRunTitle: 'Unit Tests'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'src/MyApplication/MyApplication.IntegrationTests/MyApplicationIntegrationTests.csproj'
    testRunTitle: 'Integration Tests'